#!/usr/bin/env bash

# See https://aloha.readthedocs.io/en/latest/translating/internationalization.html
# for background on this subsystem.

set -e
set -x

./manage.py makemessages --locale=en
tx push -s -r aloha.djangopo,aloha.translationsjson "$@"
