#!/usr/bin/env bash
# This tests upgrading PostgreSQL
set -e
set -x

su aloha -c /home/aloha/deployments/current/scripts/stop-server
/home/aloha/deployments/current/scripts/setup/upgrade-postgresql
su aloha -c /home/aloha/deployments/current/scripts/start-server

echo "Upgrade of PostgreSQL complete!"
exit 0
