#!/usr/bin/env bash
set -e
set -x

PGHOST=localhost PGUSER=aloha \
    "$(dirname "$0")/../scripts/setup/terminate-psql-sessions" aloha aloha_base

psql -v ON_ERROR_STOP=1 -e -h localhost postgres aloha <<EOF
DROP DATABASE IF EXISTS aloha;
CREATE DATABASE aloha TEMPLATE aloha_base;
EOF

"$(dirname "$0")/../scripts/setup/flush-memcached"

./manage.py purge_queue --all
./manage.py migrate --noinput
./manage.py get_migration_status --settings=zproject.settings --output="migration_status_dev"
./manage.py createcachetable third_party_api_results
./manage.py populate_db -n100 --threads=1
# Ensure that the local user's API key is synced from ~/.aloharc

if [ -e ~/.aloharc ]; then
    ./manage.py sync_api_key
fi
